### ISSUE TITLE
Malformed compile_commands.json

### ISSUE THREAD

**Issue by mexus** [loarabia/Clang-tutorial#26]
Hi!
I've been browsing through examples and found maybe-a-bug in "compile_commands.json" in the root of the repo: there is no ending "," at the end of the line 4 ("command": ...).
I don't know if it is crucial or anything, but I doubt it is by design also.

**Comment by loarabia** [comment]
You're absolutely right. The bug is obvious upon inspection but it turns out it doesn't really matter to llcm/clang. Looking at the YAML Parser that llvm and clang use internally it turns out that scanner and parser its using for YAML is very liberal with what it accepts as JSON. I'll get this fixed.
